server:
  port: 8585

spring:
  application:
    name: Press-lab

  datasource:
    url: jdbc:postgresql://localhost:5432/presslab?createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
